// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bfaojzmqnqblwvmupprt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJmYW9qem1xbnFibHd2bXVwcHJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MjcxNjAsImV4cCI6MjA2NDEwMzE2MH0.1WJ7sJO8XTRPfWeh2kwHCujrtitOYHbVVQMhzYrAbb4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);