// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxpyhbdtwfrkpbaogmyl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_vU7nXVoQjqstigOxJSzEWQ_1S3T1Q9T";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);